services:
  app:
    build:
      context: ./backend
    container_name: app
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./backend:/var/www/backend
    depends_on:
      - nginx
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: licoreria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
